#!/usr/bin/env bash
# Displays information about subdomains

get_info () {
    dig_cmd=$(dig "$1" | grep -A1 'ANSWER SECTION' | tail -n 1)
    
    subdomain=$(echo "$dig_cmd" | awk '{print $1;}' FS=.)
    record_type=$(echo "$dig_cmd" | awk '{print $4;}')
    ip_address=$(echo "$dig_cmd" | awk '{print $5}')


    echo "The subdomain $subdomain is a $record_type record and points to $ip_address"
}

if [ $# -eq 1 ]
then
        get_info "www.$1"
        get_info "lb-01.$1"
        get_info "web-01.$1"
        get_info "web-02.$1"
elif [ $# -eq 2 ]
then
        getinfo "$2.$1"
fi
