#!/usr/bin/env bash
# copies a file to a remote server using scp
if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" "$1" "$2@$3":~/
fi
