#!/usr/bin/env bash
# install nginx on a web server
#+ Nginx should listen on port 80
#+ When querying Nginx at its root, return a page that contains the string 'Hello World!'
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html

