#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
my_redir="\\\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "24i $my_redir" /etc/nginx/sites-available/default
sudo service nginx restart
