#!/usr/bin/env bash
# adds permanent redirection on a server via /redirect_me route
nginx_default="/etc/nginx/sites-available/default"
backup="${nginx_default}.baks"
create_backup="cp $nginx_default $backup"
restore_backup="cp $backup $nginx_default"

redr='rewrite ^/redirect_me$ https://www.github.com permanent;'

$restore_backup
$create_backup

#check if redirection rule already exists


if ! grep -Fq "$redr" $nginx_default; then
    sed -i "0,/server_name/!b; /server_name/a\    $redr" $nginx_default
    if nginx -t; then
	service nginx reload
    else
	echo "Error in nginx configuration."
	$restore_backup
    fi
else
    echo "Redirection rule already exists. No changes were made."
fi
