#!/usr/bin/env bash
# Confugure Nginx so that its HTTPs response contains a custom header(on web 01 & web-102)
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.Confugures
echo "Hello world" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
