#!/usr/bin/env bash
# Configure HAProxy so that it sends traffic to web-01 & web-02.
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo tee -a /etc/haproxy/haproxy.cfg <<EOF
frontend http-in
    bind *:80
    default_backend webservers
backend webservers
    balance roundrobin
    server web-01
    server web-02
EOF
sudo service haproxy restart
