#!/usr/bin/env bash
# Installs and configures HAProxy on lb-01 server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy=2.6\*
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend http
    bind *:80
    mode http
    option forwardfor
    default_backend my_servers

backend my_servers
    balance roundrobin
    server web-01 44.200.191.146:80 check
    server web-02 54.237.114.157:80 check
EOT
sudo service haproxy restart
