#!/usr/bin/env bash
# displays Best School 9 times then diplays Hi

COUNT=0
while [ $COUNT -lt 10 ] ; do
    echo Best School
    if [ $COUNT == 8 ]
    then
        echo "Hi"
    fi
    ((COUNT++)) || true
done
