#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59

HOUR=0
while [ $HOUR -lt 13 ] ; do
    echo Hour: $HOUR
    MINUTE=1
    while [ $MINUTE -lt 60 ] ; do
        echo $MINUTE
        ((MINUTE++)) || true
    done
    ((HOUR++)) || true
done