#!/usr/bin/env bash
# configures Ubuntu server with the below requirements
# localhost resolves to 127.0.0.2
# facebook.com resolvesto 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
