#!/usr/bin/env bash
# modifies hosts file to map localhost and facebook to new addresses
cp /etc/hosts ~/hosts.new
echo -e "localhost\t127.0.0.2\nfacebook.com\t8.8.8.8" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
