#!/usr/bin/env bash
# code to get Apache to run on the container .
# Return a page containing Hello Holberton

sudo apt update
apt-get install -y apache2
apt-get install -y apache2-utils
sudo service apache2 start